### ISSUE TITLE
error: implicit declaration of function

### ISSUE THREAD

**Issue by Hubonzi** [gfrankliu/nginx-http-reqstat#2]
[root@lua-nginx nginx-1.16.1]# patch -p1 < /app/ctglb/nginx-http-reqstat/connection.patch
[root@lua-nginx nginx-1.16.1]# ./configure --prefix=/app/ctglb/nginx --with-ld-opt="-Wl,-rpath,$LUAJIT_LIB" --add-module=/app/ctglb/ngx_devel_kit-0.3.0/ --add-module=/app/ctglb/lua-nginx-module-0.10.9rc7/ --add-module=/app/ctglb/lua-upstream-nginx-module --with-http_stub_status_module --add-module=/app/ctglb/nginx-http-reqstat

src/http/ngx_http_write_filter_module.c: In function ‘ngx_http_write_filter’:
src/http/ngx_http_write_filter_module.c:296:9: error: ‘ngx_http_top_write_filter’ undeclared (first use in this function)
     if (ngx_http_top_write_filter){
         ^
src/http/ngx_http_write_filter_module.c:296:9: note: each undeclared identifier is reported only once for each function it appears in
src/http/ngx_http_write_filter_module.c:297:7: error: implicit declaration of function ‘ngx_http_top_write_filter’ [-Werror=implicit-function-declaration]
       ngx_http_top_write_filter(r, sent);
       ^
cc1: all warnings being treated as errors
make[1]: *** [objs/src/http/ngx_http_write_filter_module.o] Error 1
make[1]: Leaving directory `/app/ctglb/install/nginx-1.16.1'
make: *** [build] Error 2

**Comment by Hubonzi** [comment]
[root@lua-nginx nginx-1.16.1]# patch -p1 < /app/ctglb/nginx-http-reqstat/connection.patch ^C
[root@lua-nginx nginx-1.16.1]# ./configure --prefix=/app/ctglb/nginx --with-ld-opt="-Wl,-rpath,$LUAJIT_LIB" --add-module=/app/ctglb/ngx_devel_kit-0.3.0/ --add-module=/app/ctglb/lua-nginx-module-0.10.9rc7/ --add-module=/app/ctglb/lua-upstream-nginx-module --with-http_stub_status_module --add-module=/app/ctglb/nginx-http-reqstat

**Comment by gfrankliu** [comment]
I tried your command but don't see the errors.
I suspect your issue is something else.
Can you first try compile nginx without any special modules?
./configure --prefix=/app/ctglb/nginx
If that works, just add reqstat module to see if it creates the error:
./configure --prefix=/app/ctglb/nginx --with-http_stub_status_module --add-module=/app/ctglb/nginx-http-reqstat

**Comment by gfrankliu** [comment]
Seems to related to GCC version.
Fixed in [this commit](https://github.com/gfrankliu/nginx-http-reqstat/commit/7d7fddc04a09080fb096420a0da8bc62d816ae84)
